name: 'Jest unit tests'
on:
  push:
    paths-ignore:
      - '**/dist/**'
      - '**/*.md'
      - '.github/**'
      - '.vscode/**'
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '21.5.0'
      - run: npm ci
      - run: npm run test
